version: '3.1'
services:
#   docker:
#        container_name: jenkins-docker
#        restart: always
#        image: docker:dind
#        environment:
#            - 'DOCKER_TLS_CERTDIR=/certs'
#        ports:
#            - '2376:2376'
#        volumes:
#            - jenkins-data:/var/jenkins_home
#            - jenkins-docker-certs:/certs/client
#        privileged: true
#
   jenkins:
        container_name: jenkins-blueocean
        restart: always
        build: 
            context: .
            dockerfile: Dockerfile
        environment:
          - 'DOCKER_HOST=tcp://172.17.0.1:2375'
          # - 'DOCKER_CERT_PATH=/certs/client'
          # - 'DOCKER_TLS_VERIFY=1'
        ports:
            - '8080:8080'
            - '50000:50000'
        volumes:
            - jenkins-data:/var/jenkins_home
            - jenkins-docker-certs:/certs/client:ro
         #   - /var/run/docker.sock:/var/run/docker.sock
#        depends_on:
#            - docker
#
volumes:
    jenkins-data:
    jenkins-docker-certs:
